# Generated by Django 3.1.7 on 2022-01-17 19:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='cibil_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='cibil_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.cibiltype'),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.country'),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='default_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.defaultyear'),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.degree'),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='degree_others',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='details_about_default',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='enduse',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.gender'),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='lawyerType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.lawyertype'),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='loan_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='loan_taken',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='marital_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.maritalstatus'),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.nationality'),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.profession'),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='qualification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.qualification'),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='repayment_history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.repaymenthistory'),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='retirement_age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(70)]),
        ),
    ]
