# Generated by Django 3.1.7 on 2021-08-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210813_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='remarks',
            field=models.CharField(default='good', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='type_of_partner',
            field=models.CharField(default='Hot', max_length=20),
        ),
    ]
