# Generated by Django 3.1.7 on 2022-01-17 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
        ('account', '0003_auto_20220118_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='additional_details_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.additionaldetails'),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.product'),
        ),
    ]
