# Generated by Django 3.1.7 on 2022-01-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20211224_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='alt_phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='leads',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='leads',
            name='loan_amt',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='leads',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='leads',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='leads',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
    ]
