# Generated by Django 3.1.7 on 2022-01-19 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_lessetype'),
        ('account', '0004_auto_20220118_0114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salotherincomes',
            old_name='addi_details_id_other_inc',
            new_name='addi_details_id',
        ),
        migrations.RenameField(
            model_name='salotherincomes',
            old_name='other_inc_det_id',
            new_name='other_inc_id',
        ),
        migrations.RemoveField(
            model_name='salotherincomes',
            name='How_old_is_agreement',
        ),
        migrations.RemoveField(
            model_name='salotherincomes',
            name='Lessee_Name',
        ),
        migrations.RemoveField(
            model_name='salotherincomes',
            name='Lessee_Type',
        ),
        migrations.RemoveField(
            model_name='salotherincomes',
            name='Will_u_make_agreement',
        ),
        migrations.RemoveField(
            model_name='salotherincomes',
            name='agreement_Type',
        ),
        migrations.RemoveField(
            model_name='salotherincomes',
            name='extension_expected_in_years',
        ),
        migrations.RemoveField(
            model_name='salotherincomes',
            name='reflection_in_ITR_acc',
        ),
        migrations.RemoveField(
            model_name='salotherincomes',
            name='reflection_in_bank_acc',
        ),
        migrations.RemoveField(
            model_name='salotherincomes',
            name='tenure_of_arguement',
        ),
        migrations.AddField(
            model_name='salotherincomes',
            name='agreement_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.agreementtype'),
        ),
        migrations.AddField(
            model_name='salotherincomes',
            name='extension_expected_years',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salotherincomes',
            name='how_old_is_agreement',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salotherincomes',
            name='lessee_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salotherincomes',
            name='lessee_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.lessetype'),
        ),
        migrations.AddField(
            model_name='salotherincomes',
            name='reflection_in_bank_account',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='salotherincomes',
            name='reflection_in_itr',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AddField(
            model_name='salotherincomes',
            name='tenure_of_agreement',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salotherincomes',
            name='will_you_make_agreement',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='salotherincomes',
            name='rent_amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='salotherincomes',
            name='rental_income',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='salotherincomes',
            name='tenure_pending',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='salotherincomes',
            name='valid_rent_agreement',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
    ]
