# Generated by Django 3.1.7 on 2022-01-19 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_paymentdelayyear'),
        ('account', '0007_auto_20220119_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalExistingCreditCard',
            fields=[
                ('existing_credit_card_id', models.AutoField(primary_key=True, serialize=False)),
                ('credit_limit', models.IntegerField()),
                ('limit_utilized', models.IntegerField()),
                ('minimum_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('credit_card_age', models.IntegerField()),
                ('payment_delay', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('moratorium_taken', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False)),
                ('addi_details_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.additionaldetails')),
                ('bank_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.bankname')),
                ('payment_delay_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.paymentdelayyear')),
            ],
        ),
        migrations.DeleteModel(
            name='SalExistingCardDetails',
        ),
    ]
