# Generated by Django 3.1.7 on 2022-01-19 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20220119_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalAdditionalOtherIncomes',
            fields=[
                ('add_oth_inc_id', models.AutoField(primary_key=True, serialize=False)),
                ('other_income', models.CharField(max_length=50)),
                ('income_amount', models.IntegerField()),
                ('addi_details_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.additionaldetails')),
            ],
        ),
        migrations.DeleteModel(
            name='SalAdditonalOtherIncome',
        ),
    ]
