# Generated by Django 3.1.7 on 2022-01-21 18:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_companyname_employmenttype_investmenttype'),
        ('account', '0009_auto_20220119_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaldetails',
            name='inc_holder',
            field=models.BooleanField(choices=[(None, 'Select Yes Or No'), (True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='additionaldetails',
            name='prop_owner',
            field=models.BooleanField(choices=[(None, 'Select Yes Or No'), (True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='proptype1',
            name='car_parking',
            field=models.BooleanField(choices=[(None, 'Select Yes Or No'), (True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='proptype1',
            name='car_parking_amt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proptype1',
            name='cc_rec',
            field=models.BooleanField(choices=[(None, 'Select Yes Or No'), (True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='proptype1',
            name='cc_rec_upto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proptype1',
            name='cost_sheet',
            field=models.BooleanField(choices=[(None, 'Select Yes Or No'), (True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AlterField(
            model_name='proptype1',
            name='cost_sheet_amt',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='proptype1',
            name='municipal_approved',
            field=models.BooleanField(choices=[(None, 'Select Yes Or No'), (True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='proptype1',
            name='pay_till_date',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='proptype1',
            name='stamp_duty',
            field=models.BooleanField(choices=[(None, 'Select Yes Or No'), (True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='proptype1',
            name='subvention_scheme',
            field=models.BooleanField(blank=True, choices=[(None, 'Select Yes Or No'), (True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='proptype2',
            name='car_parking',
            field=models.BooleanField(choices=[(None, 'Select Yes Or No'), (True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='proptype2',
            name='car_parking_amt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proptype2',
            name='cc_rec',
            field=models.BooleanField(choices=[(None, 'Select Yes Or No'), (True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='proptype2',
            name='cc_rec_upto',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proptype2',
            name='cost_sheet',
            field=models.BooleanField(choices=[(None, 'Select Yes Or No'), (True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='proptype2',
            name='cost_sheet_amt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proptype2',
            name='municipal_approved',
            field=models.BooleanField(choices=[(None, 'Select Yes Or No'), (True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='proptype2',
            name='pay_till_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='proptype2',
            name='stamp_duty',
            field=models.BooleanField(choices=[(None, 'Select Yes Or No'), (True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='proptype2',
            name='stamp_duty_amt',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='proptype3',
            name='car_parking',
            field=models.BooleanField(choices=[(None, 'Select Yes Or No'), (True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='proptype3',
            name='car_parking_amt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proptype3',
            name='cc_rec',
            field=models.BooleanField(choices=[(None, 'Select Yes Or No'), (True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='proptype3',
            name='cost_sheet',
            field=models.BooleanField(choices=[(None, 'Select Yes Or No'), (True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='proptype3',
            name='cost_sheet_amt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proptype3',
            name='municipal_approved',
            field=models.BooleanField(choices=[(None, 'Select Yes Or No'), (True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='proptype3',
            name='oc_rec',
            field=models.BooleanField(choices=[(None, 'Select Yes Or No'), (True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='proptype3',
            name='stamp_duty',
            field=models.BooleanField(choices=[(None, 'Select Yes Or No'), (True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='proptype3',
            name='stamp_duty_amt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proptype4',
            name='car_parking',
            field=models.BooleanField(choices=[(None, 'Select Yes Or No'), (True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='proptype4',
            name='car_parking_amt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proptype4',
            name='cc_available',
            field=models.BooleanField(choices=[(None, 'Select Yes Or No'), (True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='proptype4',
            name='municipal_approved',
            field=models.BooleanField(choices=[(None, 'Select Yes Or No'), (True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='proptype4',
            name='oc_rec',
            field=models.BooleanField(choices=[(None, 'Select Yes Or No'), (True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='proptype4',
            name='oc_rec_floor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proptype4',
            name='previous_aggrement_available',
            field=models.BooleanField(blank=True, choices=[(None, 'Select Yes Or No'), (True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='proptype4',
            name='property_tax_paid',
            field=models.BooleanField(blank=True, choices=[(None, 'Select Yes Or No'), (True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='proptype4',
            name='society_informed',
            field=models.BooleanField(blank=True, choices=[(None, 'Select Yes Or No'), (True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='proptype4',
            name='stamp_duty_amt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proptype4',
            name='stamp_duty_registration_paid',
            field=models.BooleanField(choices=[(None, 'Select Yes Or No'), (True, 'Yes'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='salcompanydetails',
            name='office_email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='salcompanydetails',
            name='office_phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='salexistingcreditcard',
            name='moratorium_taken',
            field=models.BooleanField(choices=[(None, 'Select Yes Or No'), (True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='salexistingcreditcard',
            name='payment_delay',
            field=models.BooleanField(choices=[(None, 'Select Yes Or No'), (True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='salexistingloandetails',
            name='any_bounces',
            field=models.BooleanField(choices=[(None, 'Select Yes Or No'), (True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='salexistingloandetails',
            name='moratorium_taken',
            field=models.BooleanField(choices=[(None, 'Select Yes Or No'), (True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='salincomedetails',
            name='deduction_choice',
            field=models.BooleanField(blank=True, choices=[(None, 'Select Yes Or No'), (True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='salotherincomes',
            name='reflection_in_bank_account',
            field=models.BooleanField(blank=True, choices=[(None, 'Select Yes Or No'), (True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='salotherincomes',
            name='reflection_in_itr',
            field=models.BooleanField(blank=True, choices=[(None, 'Select Yes Or No'), (True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='salotherincomes',
            name='valid_rent_agreement',
            field=models.BooleanField(choices=[(None, 'Select Yes Or No'), (True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='salotherincomes',
            name='will_you_make_agreement',
            field=models.BooleanField(blank=True, choices=[(None, 'Select Yes Or No'), (True, 'Yes'), (False, 'No')], null=True),
        ),
    ]
