# Generated by Django 3.1.7 on 2022-01-21 18:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20220121_2343'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalInvestments',
            fields=[
                ('sal_inv_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='SalPersonalDetails',
            fields=[
                ('per_det_id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_amount', models.IntegerField(null=True)),
                ('cibil_score', models.IntegerField(blank=True, null=True)),
                ('loan_taken', models.BooleanField(choices=[(None, 'Select Yes Or No'), (True, 'Yes'), (False, 'No')], default=False)),
                ('repayment_history', models.CharField(choices=[(None, '-- Good or Bad --'), ('Good', 'Good'), ('Bad', 'Bad')], default=None, max_length=4)),
                ('details_about_default', models.CharField(blank=True, max_length=200)),
                ('dob', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('retirement_age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(70)])),
                ('degree_others', models.CharField(blank=True, max_length=100, null=True)),
                ('enduse', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='investments',
            name='add_det_id',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='additional_details_id',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='cibil_type',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='country',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='default_year',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='lawyerType',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='repayment_history',
        ),
        migrations.RenameField(
            model_name='saladditionaldetails',
            old_name='add_det_id',
            new_name='addi_details_id',
        ),
        migrations.RenameField(
            model_name='salcompanydetails',
            old_name='nature_business',
            new_name='nature_of_business',
        ),
        migrations.RemoveField(
            model_name='saladditionaldetails',
            name='inw_cheque_return',
        ),
        migrations.RemoveField(
            model_name='saladditionaldetails',
            name='loan_enq_det',
        ),
        migrations.RemoveField(
            model_name='saladditionaldetails',
            name='loan_enq_disburse',
        ),
        migrations.RemoveField(
            model_name='salcompanydetails',
            name='add_det_id',
        ),
        migrations.RemoveField(
            model_name='salcompanydetails',
            name='comp_age',
        ),
        migrations.RemoveField(
            model_name='salcompanydetails',
            name='comp_name',
        ),
        migrations.RemoveField(
            model_name='salcompanydetails',
            name='comp_type',
        ),
        migrations.RemoveField(
            model_name='salcompanydetails',
            name='curr_exp',
        ),
        migrations.RemoveField(
            model_name='salcompanydetails',
            name='des_type',
        ),
        migrations.RemoveField(
            model_name='salcompanydetails',
            name='emp_type',
        ),
        migrations.RemoveField(
            model_name='salcompanydetails',
            name='form16',
        ),
        migrations.RemoveField(
            model_name='salcompanydetails',
            name='paid_up_cap',
        ),
        migrations.RemoveField(
            model_name='salcompanydetails',
            name='total_exp',
        ),
        migrations.AddField(
            model_name='saladditionaldetails',
            name='inward_cheque_return',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saladditionaldetails',
            name='loan_inquiry_disbursement',
            field=models.BooleanField(choices=[(None, 'Select Yes Or No'), (True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AddField(
            model_name='saladditionaldetails',
            name='loan_inquiry_disbursement_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salcompanydetails',
            name='addi_details_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.additionaldetails'),
        ),
        migrations.AddField(
            model_name='salcompanydetails',
            name='company_age',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
