# Generated by Django 3.1.7 on 2022-01-21 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_auto_20220122_0003'),
        ('account', '0011_auto_20220122_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='salcompanydetails',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.companyname'),
        ),
        migrations.AddField(
            model_name='salcompanydetails',
            name='company_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.companytype'),
        ),
        migrations.AddField(
            model_name='salcompanydetails',
            name='current_experience',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salcompanydetails',
            name='designation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.designationtype'),
        ),
        migrations.AddField(
            model_name='salcompanydetails',
            name='employment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.employmenttype'),
        ),
        migrations.AddField(
            model_name='salcompanydetails',
            name='form_16',
            field=models.BooleanField(choices=[(None, 'Select Yes Or No'), (True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AddField(
            model_name='salcompanydetails',
            name='paid_up_capital',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salcompanydetails',
            name='total_experience',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salcompanydetails',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.city'),
        ),
        migrations.DeleteModel(
            name='Investments',
        ),
        migrations.DeleteModel(
            name='PersonalDetails',
        ),
        migrations.AddField(
            model_name='salpersonaldetails',
            name='additional_details_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.additionaldetails'),
        ),
        migrations.AddField(
            model_name='salpersonaldetails',
            name='cibil_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.cibiltype'),
        ),
        migrations.AddField(
            model_name='salpersonaldetails',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.country'),
        ),
        migrations.AddField(
            model_name='salpersonaldetails',
            name='default_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.defaultyear'),
        ),
        migrations.AddField(
            model_name='salpersonaldetails',
            name='degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.degree'),
        ),
        migrations.AddField(
            model_name='salpersonaldetails',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.gender'),
        ),
        migrations.AddField(
            model_name='salpersonaldetails',
            name='lawyerType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.lawyertype'),
        ),
        migrations.AddField(
            model_name='salpersonaldetails',
            name='marital_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.maritalstatus'),
        ),
        migrations.AddField(
            model_name='salpersonaldetails',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.nationality'),
        ),
        migrations.AddField(
            model_name='salpersonaldetails',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.product'),
        ),
        migrations.AddField(
            model_name='salpersonaldetails',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.profession'),
        ),
        migrations.AddField(
            model_name='salpersonaldetails',
            name='qualification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.qualification'),
        ),
    ]
