# Generated by Django 3.1.7 on 2022-01-22 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_auto_20220122_0003'),
        ('account', '0012_auto_20220122_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='salinvestments',
            name='addi_details_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.additionaldetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salinvestments',
            name='investments',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master.investmenttype'),
            preserve_default=False,
        ),
    ]
