# Generated by Django 3.1.7 on 2022-01-22 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_productsorservices'),
        ('account', '0015_auto_20220122_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salexistingloandetails',
            name='products',
        ),
        migrations.AddField(
            model_name='salexistingloandetails',
            name='products_or_services',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='master.productsorservices'),
            preserve_default=False,
        ),
    ]
