from django.contrib import admin
from .models import *
# Register your models here.
admin.site.register(Product)
admin.site.register(SubProduct)
admin.site.register(Gender)
admin.site.register(Prefix)
admin.site.register(Relation)
admin.site.register(MaritalStatus)
admin.site.register(Qualification)
admin.site.register(Profession)
admin.site.register(Role)
admin.site.register(CustomerType)
admin.site.register(DesignationType)
admin.site.register(CompanyType)
admin.site.register(SalaryType)
admin.site.register(ResidenceType)
admin.site.register(BankName)
admin.site.register(LeadSource)
admin.site.register(Degree)
admin.site.register(Nationality)
admin.site.register(State)
admin.site.register(City)
admin.site.register(ApplicantType)
admin.site.register(PropertyIn)
admin.site.register(Status)
admin.site.register(NatureOfBusiness)
admin.site.register(AYYear)
admin.site.register(AgreementType)
admin.site.register(StageOfConstruction)
admin.site.register(RejectionType)

