# Generated by Django 3.1.7 on 2021-08-13 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomeLoan', '0002_remove_income_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HomeLoan.productsandpolicy'),
        ),
    ]
