# Generated by Django 3.1.7 on 2022-01-28 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0009_cibilloantype'),
        ('HomeLoan', '0003_auto_20220128_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cibil',
            name='bank_id',
        ),
        migrations.RemoveField(
            model_name='cibil',
            name='cibil_range_max',
        ),
        migrations.RemoveField(
            model_name='cibil',
            name='cibil_range_min',
        ),
        migrations.RemoveField(
            model_name='productsandpolicy',
            name='bank_id',
        ),
        migrations.RemoveField(
            model_name='productsandpolicy',
            name='company_type',
        ),
        migrations.RemoveField(
            model_name='productsandpolicy',
            name='customer_type',
        ),
        migrations.RemoveField(
            model_name='productsandpolicy',
            name='maximum_loan_amount',
        ),
        migrations.RemoveField(
            model_name='productsandpolicy',
            name='minimum_age',
        ),
        migrations.RemoveField(
            model_name='productsandpolicy',
            name='minimum_loan_amount',
        ),
        migrations.RemoveField(
            model_name='productsandpolicy',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='productsandpolicy',
            name='retirement_age',
        ),
        migrations.RemoveField(
            model_name='productsandpolicy',
            name='total_experience',
        ),
        migrations.AddField(
            model_name='cibil',
            name='basic_details_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HomeLoan.hlbasicdetails'),
        ),
        migrations.AddField(
            model_name='cibil',
            name='cibil_loan_type_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master.cibilloantype'),
        ),
        migrations.AddField(
            model_name='cibil',
            name='max_amount',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cibil',
            name='max_cibil',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cibil',
            name='max_rate',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cibil',
            name='min_amount',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cibil',
            name='min_cibil',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cibil',
            name='min_rate',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cibil',
            name='processing_fees',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hlbasicdetails',
            name='pid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='HomeLoan.productsandpolicy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productsandpolicy',
            name='bank_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.bankname'),
        ),
        migrations.AlterField(
            model_name='productsandpolicy',
            name='ineffective_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
