# Generated by Django 3.1.7 on 2021-08-13 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeLoan', '0005_property_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='product',
        ),
    ]
