# Generated by Django 3.1.7 on 2021-08-15 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomeLoan', '0006_remove_property_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankcodes',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HomeLoan.productsandpolicy'),
        ),
        migrations.AddField(
            model_name='customerdesignation',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HomeLoan.productsandpolicy'),
        ),
        migrations.AddField(
            model_name='fees',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HomeLoan.productsandpolicy'),
        ),
        migrations.AddField(
            model_name='income',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HomeLoan.productsandpolicy'),
        ),
        migrations.AddField(
            model_name='loantowardsvaluation',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HomeLoan.productsandpolicy'),
        ),
        migrations.AddField(
            model_name='obligation',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HomeLoan.productsandpolicy'),
        ),
        migrations.AddField(
            model_name='otherdetails',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HomeLoan.productsandpolicy'),
        ),
        migrations.AddField(
            model_name='property',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HomeLoan.productsandpolicy'),
        ),
    ]
