# Generated by Django 3.1.7 on 2021-08-15 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeLoan', '0007_auto_20210815_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsandpolicy',
            name='bank_id',
        ),
        migrations.RemoveField(
            model_name='productsandpolicy',
            name='company_type',
        ),
        migrations.RemoveField(
            model_name='customerdesignation',
            name='product',
        ),
        migrations.RemoveField(
            model_name='fees',
            name='product',
        ),
        migrations.RemoveField(
            model_name='income',
            name='product',
        ),
        migrations.RemoveField(
            model_name='loantowardsvaluation',
            name='product',
        ),
        migrations.RemoveField(
            model_name='obligation',
            name='product',
        ),
        migrations.RemoveField(
            model_name='otherdetails',
            name='product',
        ),
        migrations.RemoveField(
            model_name='property',
            name='product',
        ),
        migrations.DeleteModel(
            name='BankCodes',
        ),
        migrations.DeleteModel(
            name='ProductsAndPolicy',
        ),
    ]
