# Generated by Django 3.1.7 on 2021-08-15 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomeLoan', '0008_auto_20210815_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsAndPolicy',
            fields=[
                ('prod_id', models.AutoField(primary_key=True, serialize=False)),
                ('productandpolicy_name', models.CharField(max_length=50)),
                ('prod_name', models.CharField(max_length=25)),
                ('sub_product', models.CharField(max_length=25)),
                ('customer_type', models.CharField(max_length=25)),
                ('nationality', models.CharField(max_length=25)),
                ('minimum_age', models.CharField(max_length=25)),
                ('retirement_age', models.CharField(max_length=25)),
                ('minimum_loan_amount', models.CharField(max_length=25)),
                ('maximum_loan_amount', models.CharField(max_length=25)),
                ('total_experience', models.CharField(max_length=25)),
                ('effective_date', models.DateField(auto_now_add=True)),
                ('ineffective_date', models.DateField(null=True)),
                ('bank_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HomeLoan.bank')),
                ('company_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HomeLoan.company')),
            ],
        ),
        migrations.CreateModel(
            name='BankCodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=25)),
                ('name_of_company', models.CharField(max_length=50)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HomeLoan.bank')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HomeLoan.productsandpolicy')),
            ],
        ),
        migrations.AddField(
            model_name='customerdesignation',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HomeLoan.productsandpolicy'),
        ),
        migrations.AddField(
            model_name='fees',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HomeLoan.productsandpolicy'),
        ),
        migrations.AddField(
            model_name='income',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HomeLoan.productsandpolicy'),
        ),
        migrations.AddField(
            model_name='loantowardsvaluation',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HomeLoan.productsandpolicy'),
        ),
        migrations.AddField(
            model_name='obligation',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HomeLoan.productsandpolicy'),
        ),
        migrations.AddField(
            model_name='otherdetails',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HomeLoan.productsandpolicy'),
        ),
        migrations.AddField(
            model_name='property',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HomeLoan.productsandpolicy'),
        ),
    ]
