# Generated by Django 3.1.7 on 2021-08-16 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeLoan', '0011_auto_20210815_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsandpolicy',
            name='company_type',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
