# Generated by Django 3.1.7 on 2021-08-16 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HomeLoan', '0012_auto_20210816_0602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('comp_id', models.AutoField(primary_key=True, serialize=False)),
                ('comp_type', models.CharField(max_length=25)),
                ('bank_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HomeLoan.bank')),
            ],
        ),
        migrations.AddField(
            model_name='productsandpolicy',
            name='company_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HomeLoan.company'),
        ),
    ]
