# Generated by Django 3.1.7 on 2021-08-16 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_remove_city_city_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_name',
            field=models.CharField(default='', max_length=25),
        ),
    ]
