# Generated by Django 3.1.7 on 2022-01-21 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_paymentdelayyear'),
    ]

    operations = [
    ]
