# Generated by Django 3.1.7 on 2022-01-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20220122_0003'),
        ('master', '0005_companyname_employmenttype_investmenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('effective_date', models.DateField(null=True)),
                ('ineffective_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_type', models.CharField(max_length=30)),
                ('effective_date', models.DateField(null=True)),
                ('ineffective_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_type', models.CharField(max_length=30)),
                ('effective_date', models.DateField(null=True)),
                ('ineffective_date', models.DateField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='RepaymentHistory',
        ),
    ]
