# Generated by Django 3.1.7 on 2022-01-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_auto_20220122_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsOrServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products_or_services', models.CharField(max_length=30)),
                ('effective_date', models.DateField(null=True)),
                ('ineffective_date', models.DateField(null=True)),
            ],
        ),
    ]
